### ISSUE TITLE
[BUILD][CMake] OPENEXR_HALF_LIBRARY and  OPENEXR_ILMIMF_LIBRARY are set to `NOTFOUND`

### ISSUE THREAD

**Issue by worthless443** [mcneel/cycles#6]
On my gentoo system, I have all the dependencies (e.g. the aforementioned opener)
```
[ebuild   R    ] media-libs/openexr-3.1.4-r1
```
I'm not sure what extra to openexr I need to install to get these variables to be not empty. For example, searching for `ILMIMF` returns nothing relevant to me. 

Any suggestions on what Libs do I need to install, even if one could link the source to the respective libraries?

**Comment by jesterKing** [comment]
We are not using CMake or such files for our use of Cycles. I would suggest to use the upstream repository at https://developer.blender.org/diffusion/C/
